#include "aireportpage.h"
#include "core/aireporter.h"
#include "core/database.h"

#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFrame>
#include <QSettings>
#include <QFileDialog>
#include <QFile>
#include <QTextStream>
#include <QMessageBox>
#include <QDate>
#include <QDateTime>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QUuid>
#include <algorithm>

namespace {

WeeklyReport reportFromJson(const QJsonObject &obj)
{
    WeeklyReport report;
    report.reportId = obj.value(QStringLiteral("reportId")).toString();
    report.startDate = obj.value(QStringLiteral("startDate")).toString();
    report.endDate = obj.value(QStringLiteral("endDate")).toString();
    report.reportType = obj.value(QStringLiteral("reportType")).toString();
    report.content = obj.value(QStringLiteral("content")).toString();
    report.createdAt = obj.value(QStringLiteral("createdAt")).toString();
    report.serialNumber = obj.value(QStringLiteral("serialNumber")).toInt();
    report.isAutoGenerated = obj.value(QStringLiteral("isAutoGenerated")).toBool();

    if (report.reportId.isEmpty()) {
        report.reportId = QUuid::createUuid().toString(QUuid::WithoutBraces);
    }
    if (report.createdAt.isEmpty()) {
        report.createdAt = report.endDate + QStringLiteral(" 12:00:00");
    }
    if (report.serialNumber <= 0) {
        report.serialNumber = 1;
    }
    if (report.reportType.isEmpty()) {
        report.reportType = QStringLiteral("weekly");
    }
    return report;
}

QJsonObject reportToJson(const WeeklyReport &report)
{
    QJsonObject obj;
    obj[QStringLiteral("reportId")] = report.reportId;
    obj[QStringLiteral("startDate")] = report.startDate;
    obj[QStringLiteral("endDate")] = report.endDate;
    obj[QStringLiteral("reportType")] = report.reportType;
    obj[QStringLiteral("content")] = report.content;
    obj[QStringLiteral("createdAt")] = report.createdAt;
    obj[QStringLiteral("serialNumber")] = report.serialNumber;
    obj[QStringLiteral("isAutoGenerated")] = report.isAutoGenerated;
    return obj;
}

} // namespace

AIReportPage::AIReportPage(Database *database, QWidget *parent)
    : QWidget(parent)
    , m_database(database)
{
    m_reporter = new AIReporter(this);

    auto *mainLayout = new QVBoxLayout(this);
    mainLayout->setContentsMargins(20, 20, 20, 20);
    mainLayout->setSpacing(12);

    auto *title = new QLabel(QStringLiteral("使用分析报告"), this);
    title->setStyleSheet(QStringLiteral("font-size: 20px; font-weight: 600;"));
    mainLayout->addWidget(title);

    auto *subtitle = new QLabel(QStringLiteral("基于屏幕使用数据生成的日报与周报"), this);
    subtitle->setObjectName(QStringLiteral("aiReportSubtitle"));
    mainLayout->addWidget(subtitle);

    auto *buttonRow = new QFrame(this);
    buttonRow->setObjectName(QStringLiteral("aiReportButtonRow"));
    auto *buttonLayout = new QHBoxLayout(buttonRow);
    buttonLayout->setContentsMargins(14, 12, 14, 12);
    buttonLayout->setSpacing(12);

    m_generateTodayButton = new QPushButton(QStringLiteral("生成今日分析"), buttonRow);
    m_generateWeekButton = new QPushButton(QStringLiteral("生成本周分析"), buttonRow);
    m_exportButton = new QPushButton(QStringLiteral("导出全部"), buttonRow);
    m_statusLabel = new QLabel(buttonRow);
    m_statusLabel->setObjectName(QStringLiteral("aiReportStatus"));

    m_generateTodayButton->setCursor(Qt::PointingHandCursor);
    m_generateWeekButton->setCursor(Qt::PointingHandCursor);
    m_exportButton->setCursor(Qt::PointingHandCursor);
    m_exportButton->setEnabled(false);

    connect(m_generateTodayButton, &QPushButton::clicked, this, &AIReportPage::onGenerateTodayClicked);
    connect(m_generateWeekButton, &QPushButton::clicked, this, &AIReportPage::onGenerateWeekClicked);
    connect(m_exportButton, &QPushButton::clicked, this, &AIReportPage::onExportClicked);

    buttonLayout->addWidget(m_generateTodayButton);
    buttonLayout->addWidget(m_generateWeekButton);
    buttonLayout->addWidget(m_exportButton);
    buttonLayout->addWidget(m_statusLabel);
    buttonLayout->addStretch();
    mainLayout->addWidget(buttonRow);

    m_scrollArea = new QScrollArea(this);
    m_scrollArea->setWidgetResizable(true);

    m_reportsContainer = new QWidget(m_scrollArea);
    m_reportsLayout = new QVBoxLayout(m_reportsContainer);
    m_reportsLayout->setContentsMargins(0, 0, 10, 0);
    m_reportsLayout->setSpacing(12);
    m_reportsLayout->addStretch();

    m_scrollArea->setWidget(m_reportsContainer);
    mainLayout->addWidget(m_scrollArea, 1);

    connect(m_reporter, &AIReporter::reportGenerated, this, &AIReportPage::onReportGenerated);
    connect(m_reporter, &AIReporter::reportFailed, this, &AIReportPage::onReportFailed);
    connect(m_reporter, &AIReporter::requestProgress, this, &AIReportPage::onRequestProgress);

    loadReports();
    applyTheme(m_theme);
}

void AIReportPage::applyTheme(const AppThemeColors &theme)
{
    m_theme = theme;
    setStyleSheet(aiReportPageStyleSheet(theme));
    m_scrollArea->setStyleSheet(scrollAreaStyleSheet(theme));
    m_generateTodayButton->setStyleSheet(primaryButtonStyleSheet(theme));
    m_generateWeekButton->setStyleSheet(primaryButtonStyleSheet(theme));
    m_exportButton->setStyleSheet(primaryButtonStyleSheet(theme));
    rebuildReportBlocks();
}

void AIReportPage::setAIEnabled(bool enabled)
{
    m_aiEnabled = enabled;
    m_generateTodayButton->setEnabled(enabled);
    m_generateWeekButton->setEnabled(enabled);

    if (!enabled) {
        m_statusLabel->setText(QStringLiteral("请在设置中启用「分析报告」功能"));
    } else {
        m_statusLabel->setText(QString());
    }
}

void AIReportPage::setApiKey(const QString &apiKey)
{
    if (m_reporter) {
        m_reporter->setApiKey(apiKey);
    }
}

void AIReportPage::checkAndAutoGenerate()
{
    if (!m_aiEnabled || !m_database) {
        return;
    }

    QSettings settings(QStringLiteral("ScreenTime"), QStringLiteral("ScreenTime"));
    if (settings.value(QStringLiteral("ai/deepseek_api_key")).toString().isEmpty()) {
        return;
    }

    const QDate today = QDate::currentDate();
    const QString todayText = today.toString(QStringLiteral("yyyy-MM-dd"));

    if (settings.value(QStringLiteral("ai/auto_daily"), false).toBool()) {
        const QString lastDaily = settings.value(QStringLiteral("ai/last_auto_daily_date")).toString();
        if (lastDaily != todayText) {
            settings.setValue(QStringLiteral("ai/last_auto_daily_date"), todayText);
            triggerGenerate(ReportKind::Daily, true);
            return;
        }
    }

    if (settings.value(QStringLiteral("ai/auto_weekly"), false).toBool()
        && today.dayOfWeek() == Qt::Sunday) {
        const QString lastWeekly = settings.value(QStringLiteral("ai/last_auto_weekly_date")).toString();
        if (lastWeekly != todayText) {
            settings.setValue(QStringLiteral("ai/last_auto_weekly_date"), todayText);
            triggerGenerate(ReportKind::Weekly, true);
        }
    }
}

void AIReportPage::onGenerateTodayClicked()
{
    triggerGenerate(ReportKind::Daily, false);
}

void AIReportPage::onGenerateWeekClicked()
{
    triggerGenerate(ReportKind::Weekly, false);
}

bool AIReportPage::triggerGenerate(ReportKind kind, bool autoGenerated)
{
    if (!m_aiEnabled || !m_database) {
        if (!autoGenerated) {
            QMessageBox::warning(this, QStringLiteral("提示"), QStringLiteral("请先在设置中启用「分析报告」功能"));
        }
        return false;
    }

    QSettings settings(QStringLiteral("ScreenTime"), QStringLiteral("ScreenTime"));
    const QString apiKey = settings.value(QStringLiteral("ai/deepseek_api_key")).toString();
    if (apiKey.isEmpty()) {
        if (!autoGenerated) {
            QMessageBox::warning(this, QStringLiteral("提示"), QStringLiteral("请先在设置中填写 DeepSeek API Key"));
        }
        return false;
    }

    m_reporter->setApiKey(apiKey);
    m_pendingReportKind = kind;
    m_pendingAutoGenerated = autoGenerated;

    if (kind == ReportKind::Daily) {
        m_generateTodayButton->setEnabled(false);
        m_statusLabel->setText(autoGenerated ? QStringLiteral("正在自动生成今日分析...")
                                               : QStringLiteral("正在生成今日分析..."));
        m_reporter->generateWeeklyReport(m_database->queryToday(), {});
    } else {
        m_generateWeekButton->setEnabled(false);
        m_statusLabel->setText(autoGenerated ? QStringLiteral("正在自动生成本周分析...")
                                               : QStringLiteral("正在生成本周分析..."));
        m_reporter->generateWeeklyReport(m_database->queryWeekly(), m_database->queryPreviousWeek());
    }

    return true;
}

void AIReportPage::onReportGenerated(const QString &report)
{
    m_generateTodayButton->setEnabled(m_aiEnabled);
    m_generateWeekButton->setEnabled(m_aiEnabled);
    m_statusLabel->setText(QStringLiteral("生成完成"));

    const WeeklyReport newReport = buildReportFromResponse(report, m_pendingReportKind, m_pendingAutoGenerated);
    m_pendingAutoGenerated = false;

    saveReport(newReport);
    addReportBlock(newReport);
    m_exportButton->setEnabled(true);
}

void AIReportPage::onReportFailed(const QString &error)
{
    m_generateTodayButton->setEnabled(m_aiEnabled);
    m_generateWeekButton->setEnabled(m_aiEnabled);
    m_pendingAutoGenerated = false;
    m_statusLabel->setText(QStringLiteral("生成失败: %1").arg(error));
}

void AIReportPage::onRequestProgress(qint64 bytesReceived, qint64 bytesTotal)
{
    if (bytesTotal > 0) {
        const int percent = bytesReceived * 100 / bytesTotal;
        m_statusLabel->setText(QStringLiteral("接收中 %1%").arg(percent));
    }
}

void AIReportPage::onExportClicked()
{
    const QString fileName = QFileDialog::getSaveFileName(
        this,
        QStringLiteral("导出分析报告"),
        QStringLiteral("使用分析报告_%1.md").arg(QDate::currentDate().toString(QStringLiteral("yyyy-MM-dd"))),
        QStringLiteral("Markdown 文件 (*.md)"));

    if (fileName.isEmpty()) {
        return;
    }

    QFile file(fileName);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QMessageBox::warning(this, QStringLiteral("错误"), QStringLiteral("无法创建文件"));
        return;
    }

    QTextStream stream(&file);
    stream.setEncoding(QStringConverter::Utf8);

    for (const WeeklyReport &report : m_reports) {
        stream << QStringLiteral("## %1\n\n").arg(reportTitleText(report));
        stream << report.content << QStringLiteral("\n\n---\n\n");
    }

    file.close();
    QMessageBox::information(this, QStringLiteral("成功"), QStringLiteral("分析报告已导出"));
}

void AIReportPage::loadReports()
{
    QSettings settings(QStringLiteral("ScreenTime"), QStringLiteral("ScreenTime"));
    const QByteArray data = settings.value(QStringLiteral("ai/reports")).toByteArray();
    if (data.isEmpty()) {
        return;
    }

    QJsonParseError error;
    const QJsonDocument doc = QJsonDocument::fromJson(data, &error);
    if (error.error != QJsonParseError::NoError) {
        return;
    }

    m_reports.clear();
    const QJsonArray array = doc.array();
    for (const QJsonValue &value : array) {
        m_reports.append(reportFromJson(value.toObject()));
    }

    sortReportsNewestFirst();
    rebuildReportBlocks();

    if (!m_reports.isEmpty()) {
        m_exportButton->setEnabled(true);
    }
}

void AIReportPage::persistReports()
{
    QJsonArray array;
    for (const WeeklyReport &report : m_reports) {
        array.append(reportToJson(report));
    }

    QSettings settings(QStringLiteral("ScreenTime"), QStringLiteral("ScreenTime"));
    settings.setValue(QStringLiteral("ai/reports"), QJsonDocument(array).toJson());
}

void AIReportPage::saveReport(const WeeklyReport &report)
{
    m_reports.prepend(report);
    persistReports();
}

void AIReportPage::sortReportsNewestFirst()
{
    std::sort(m_reports.begin(), m_reports.end(), [](const WeeklyReport &a, const WeeklyReport &b) {
        if (a.createdAt != b.createdAt) {
            return a.createdAt > b.createdAt;
        }
        return a.serialNumber > b.serialNumber;
    });
}

int AIReportPage::nextSerialNumberForDate(const QDate &date) const
{
    const QString dateText = date.toString(QStringLiteral("yyyy-MM-dd"));
    int maxSerial = 0;
    for (const WeeklyReport &report : m_reports) {
        if (report.endDate == dateText || report.createdAt.startsWith(dateText)) {
            maxSerial = qMax(maxSerial, report.serialNumber);
        }
    }
    return maxSerial + 1;
}

WeeklyReport AIReportPage::buildReportFromResponse(const QString &report,
                                                   ReportKind kind,
                                                   bool autoGenerated) const
{
    const QDate today = QDate::currentDate();
    const QString todayText = today.toString(QStringLiteral("yyyy-MM-dd"));

    WeeklyReport newReport;
    newReport.reportId = QUuid::createUuid().toString(QUuid::WithoutBraces);
    newReport.createdAt = QDateTime::currentDateTime().toString(QStringLiteral("yyyy-MM-dd HH:mm:ss"));
    newReport.serialNumber = nextSerialNumberForDate(today);
    newReport.isAutoGenerated = autoGenerated;
    newReport.content = formatReportContent(report, kind == ReportKind::Daily ? QStringLiteral("daily")
                                                                            : QStringLiteral("weekly"));

    if (kind == ReportKind::Daily) {
        newReport.reportType = QStringLiteral("daily");
        newReport.startDate = todayText;
        newReport.endDate = todayText;
    } else {
        newReport.reportType = QStringLiteral("weekly");
        newReport.startDate = today.addDays(-6).toString(QStringLiteral("yyyy-MM-dd"));
        newReport.endDate = todayText;
    }

    return newReport;
}

QString AIReportPage::reportTitleText(const WeeklyReport &report) const
{
    const QString numberText = QStringLiteral("%1 #%2").arg(report.endDate, QString::number(report.serialNumber));

    if (report.reportType == QStringLiteral("daily")) {
        return QStringLiteral("%1 · 今日使用分析").arg(numberText);
    }

    const QDate start = QDate::fromString(report.startDate, QStringLiteral("yyyy-MM-dd"));
    const QDate end = QDate::fromString(report.endDate, QStringLiteral("yyyy-MM-dd"));
    if (start.isValid() && end.isValid()) {
        return QStringLiteral("%1 · 七天使用分析（%2 至 %3）")
            .arg(numberText,
                 start.toString(QStringLiteral("MM-dd")),
                 end.toString(QStringLiteral("MM-dd")));
    }

    return QStringLiteral("%1 · 七天使用分析").arg(numberText);
}

void AIReportPage::addReportBlock(const WeeklyReport &report)
{
    auto *block = new QFrame(m_reportsContainer);
    block->setProperty("reportId", report.reportId);
    block->setStyleSheet(aiReportBlockStyleSheet(m_theme));

    auto *blockLayout = new QVBoxLayout(block);
    blockLayout->setContentsMargins(16, 12, 16, 12);
    blockLayout->setSpacing(8);

    auto *headerRow = new QHBoxLayout();
    headerRow->setSpacing(8);

    auto *titleLabel = new QLabel(reportTitleText(report), block);
    titleLabel->setObjectName(QStringLiteral("aiReportBlockTitle"));
    titleLabel->setWordWrap(true);

    auto *deleteButton = new QPushButton(QStringLiteral("×"), block);
    deleteButton->setObjectName(QStringLiteral("deleteReportButton"));
    deleteButton->setCursor(Qt::PointingHandCursor);
    deleteButton->setToolTip(QStringLiteral("删除此报告"));
    connect(deleteButton, &QPushButton::clicked, this, [this, reportId = report.reportId]() {
        const auto answer = QMessageBox::question(
            this,
            QStringLiteral("删除报告"),
            QStringLiteral("确定删除这份分析报告吗？此操作不可恢复。"),
            QMessageBox::Yes | QMessageBox::No,
            QMessageBox::No);
        if (answer == QMessageBox::Yes) {
            removeReport(reportId);
        }
    });

    headerRow->addWidget(titleLabel, 1);
    headerRow->addWidget(deleteButton, 0, Qt::AlignTop);
    blockLayout->addLayout(headerRow);

    auto *contentLabel = new QLabel(report.content, block);
    contentLabel->setObjectName(QStringLiteral("aiReportBlockContent"));
    contentLabel->setWordWrap(true);
    blockLayout->addWidget(contentLabel);

    if (report.isAutoGenerated) {
        auto *autoLabel = new QLabel(QStringLiteral("自动生成"), block);
        autoLabel->setObjectName(QStringLiteral("aiReportAutoTag"));
        blockLayout->addWidget(autoLabel);
    }

    m_reportsLayout->insertWidget(0, block);
}

void AIReportPage::rebuildReportBlocks()
{
    while (m_reportsLayout->count() > 1) {
        QLayoutItem *item = m_reportsLayout->takeAt(0);
        if (item->widget()) {
            item->widget()->deleteLater();
        }
        delete item;
    }

    for (int i = m_reports.size() - 1; i >= 0; --i) {
        addReportBlock(m_reports.at(i));
    }
}

void AIReportPage::removeReport(const QString &reportId)
{
    m_reports.erase(
        std::remove_if(m_reports.begin(), m_reports.end(),
                       [&reportId](const WeeklyReport &report) { return report.reportId == reportId; }),
        m_reports.end());

    persistReports();

    for (int i = 0; i < m_reportsLayout->count() - 1; ++i) {
        QWidget *widget = m_reportsLayout->itemAt(i)->widget();
        if (widget && widget->property("reportId").toString() == reportId) {
            m_reportsLayout->takeAt(i);
            widget->deleteLater();
            break;
        }
    }

    if (m_reports.isEmpty()) {
        m_exportButton->setEnabled(false);
    }
}

QString AIReportPage::formatReportContent(const QString &aiResponse, const QString &reportType) const
{
    Q_UNUSED(reportType);
    return aiResponse;
}
