#ifndef AIREPORTPAGE_H
#define AIREPORTPAGE_H

#include <QWidget>
#include <QPushButton>
#include <QLabel>
#include <QScrollArea>
#include <QVBoxLayout>

#include "apptheme.h"

class AIReporter;
class Database;

struct WeeklyReport {
    QString reportId;
    QString startDate;
    QString endDate;
    QString reportType; // "daily" or "weekly"
    QString content;
    QString createdAt;
    int serialNumber = 0;
    bool isAutoGenerated = false;
};

class AIReportPage : public QWidget
{
    Q_OBJECT

public:
    explicit AIReportPage(Database *database, QWidget *parent = nullptr);
    ~AIReportPage() override = default;

    void setAIEnabled(bool enabled);
    void setApiKey(const QString &apiKey);
    void checkAndAutoGenerate();
    void applyTheme(const AppThemeColors &theme);

private slots:
    void onGenerateTodayClicked();
    void onGenerateWeekClicked();
    void onReportGenerated(const QString &report);
    void onReportFailed(const QString &error);
    void onRequestProgress(qint64 bytesReceived, qint64 bytesTotal);
    void onExportClicked();

private:
    enum class ReportKind {
        Daily,
        Weekly
    };

    bool triggerGenerate(ReportKind kind, bool autoGenerated);
    void loadReports();
    void persistReports();
    void saveReport(const WeeklyReport &report);
    void addReportBlock(const WeeklyReport &report);
    void rebuildReportBlocks();
    void removeReport(const QString &reportId);
    void sortReportsNewestFirst();
    int nextSerialNumberForDate(const QDate &date) const;
    QString reportTitleText(const WeeklyReport &report) const;
    WeeklyReport buildReportFromResponse(const QString &report, ReportKind kind, bool autoGenerated) const;
    QString formatReportContent(const QString &aiResponse, const QString &reportType) const;

    Database *m_database = nullptr;
    AIReporter *m_reporter = nullptr;
    bool m_aiEnabled = false;
    AppThemeColors m_theme = appThemeColors(AppThemeKind::Dark);
    ReportKind m_pendingReportKind = ReportKind::Weekly;
    bool m_pendingAutoGenerated = false;

    QScrollArea *m_scrollArea = nullptr;
    QWidget *m_reportsContainer = nullptr;
    QVBoxLayout *m_reportsLayout = nullptr;

    QPushButton *m_generateTodayButton = nullptr;
    QPushButton *m_generateWeekButton = nullptr;
    QPushButton *m_exportButton = nullptr;
    QLabel *m_statusLabel = nullptr;

    QList<WeeklyReport> m_reports;
};

#endif // AIREPORTPAGE_H
